[build]
  publish = "dist"
  command = "npm ci && npm run build"
  
[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--production=false"
  CI = "true"
  NETLIFY_CACHE_NEXTJS = "false"
  NETLIFY_SKIP_EDGE_HANDLERS_CACHE = "true"
  ROLLUP_NO_NATIVE = "true"
  NPM_CONFIG_IGNORE_OPTIONAL = "true"
  
[functions]
  external_node_modules = []
  included_files = ["netlify/functions/**"]
  
[functions."*"]
   node_bundler = "esbuild"
   # No external dependencies - using native Node.js modules only
  
[functions.environment]
  NODE_ENV = "production"
  NETLIFY_PURGE_CACHE = "true"

# API redirects for Netlify Functions
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/generate-image"
  to = "/.netlify/functions/image"
  status = 200

[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200

# Catch-all redirect for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 8080
  publish = "dist"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; img-src 'self' data: https:; connect-src 'self' https: wss:; font-src 'self' data: https://fonts.gstatic.com;"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"